name: string_validator
version: 0.2.0-nullsafety.0
description: Dart library for validating and sanitizing strings, especially those from user input.
homepage: https://github.com/suragch/string_validator

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  
dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.11